import './globals.css'
import { Metadata } from 'next'

//importing font to be applied globally
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
//in the <body> is how to apply fonts globally